### ISSUE TITLE
Failure when running the add_users playbook

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1394]
`fatal: [ad]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via PSRP: SOCKSHTTPConnectionPool(host='10.2.3.4', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSConnection object at 0x7facbbc907c0>, 'Connection to 10.2.3.4 timed out. (connect timeout=30)'))", "unreachable": true
`

**Comment by xpillons** [comment]
- with telnet check if port 22 is open between deployer and jumpbox
- ssh on jumpbox and check if port 5985 is open to ad
- list all ssh session on the deployer and kill all the tunnel over port 5985
- on deployer delete .ssh/known_hosts

**Comment by matt-chan** [comment]
Hi @xpillons , I found the cause!

If you have a playbook that was cancelled or died, the PSRP tunnel remains open and the localhost:5985 socket stays active. The add_users (and ad) playbooks fail to check to see if that port is already in use. They just say "changed".  If you have a second cluster being configured on the same deployer VM, then the second cluster will end up connecting to the first VM. 

If you run the "open tunnel" task manually, you get 

``` ssh -i hpcadmin_id_rsa -fN -D localhost:5985 -p 2222 -o StrictHostKeyChecking=no hpcadmin@20.97.52.61
bind [127.0.0.1]:5985: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 5985
Could not request local forwarding.
``` 

Maybe a workaround would be to run the "close tunnel" task first before starting the "open tunnel" task. (This would make threading a problem for multiple users on the same deployer). Another option is to randomize the PSRP port. A third option might be to have a context handler (not sure ansible supports this), like how python deals with file handlers. I think minimally though it would be good to change the playbook to detect the forwarding failure and report that error instead of "changed"

**Comment by xpillons** [comment]
Great you have solved it.
Multi-environment deployment from a single machine is not a scenario necessarily well covered. Making sure the tunnel is closed before starting will be the safer solution.
Best would be to have a dedicated deployer VM per environment or use a CI/CD with self-host agent to apply configuration updates.

**Comment by matt-chan** [comment]
I think we will run into this scenario pretty often if we end up doing blue/green upgrades though? The CI/CD self-hosted agent is what we want to get to in the near future. We'll have to figure out blue/green upgrades first for our use case I think though.

**Comment by xpillons** [comment]
so tunnel is closed before opening a new one. It won't solve parallels deployment, but we are not design for.
