### ISSUE TITLE
Set /usr/share/Modules/modulefiles in the default module use path

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#285]
with Lmod being installed it would be useful to add the path containing the modules from the HPC image in the default module path
/usr/share/Modules/modulefiles

**Comment by ltalirz** [comment]
Indeed, I just noticed that this breaks the spack setup instructions because the `configure.sh` script from azurehpc [points to an openmpi lmod module](https://github.com/Azure/azurehpc/blob/022db38f0ef42fb6f050e03be0667e947a5997b1/experimental/azhop/spack/configure.sh#L20-L22).

Should this be added [here](https://github.com/Azure/az-hop/blob/main/packer/scripts/centos/hpc_image.sh) ?

**Comment by xpillons** [comment]
the hpc_image script is only used when building custom images and is not used by default. A better place would be in the clutser-init script called each time a machine is started https://github.com/Azure/az-hop/blob/main/playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2
