### ISSUE TITLE
Replace User Managed Identity with System Managed Identity

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#862]

**Comment by matt-chan** [comment]
Hi Xavier,

This bug bit us today. We were deploying to an internal subscription that had an Azure Policy set which automatically creates a system-assigned MSI whenever a user-assigned MSI is created. It also conveniently didn't assign any permissions for the new identity.

On the ccportal, cyclecloud will default to using the system MSI instead of the user MSI. I looked into the cyclecloud cli, but it has no ability to distinguish between the two identities.

The bug presented as
```
**** Error: Invalid Azure credentials provided: The client '<system-assigned MSI ID>' with object id '<system-assigned MSI' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/read' over scope '/subscriptions/<sub>' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

Unfortunately it took quite awhile to hunt down because I didn't realize the ID was for the system MSI and not the user MSI...

Would it be hard to switch to a system MSI to side-step this problem in the future?

Thanks!
Matt

**Comment by matt-chan** [comment]
Hi @xpillons bumping to revive issue.

**Comment by xpillons** [comment]
Hi @matt-chan, just back from holidays. This is definitively an issue with enterprise policies being set to automatically add System Managed Identity. I'm bumping the priority of this.

**Comment by bsantacruzms** [comment]
Contacting @matt-chan to obtain details regarding the enterprise policy that is causing the error.
